spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postebin_test
    username: postgres
    password: postgres

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 3000MB

  test:
    database:
      replace: none